GO_EASY_ON_ME = 1
include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ProfessionalAutoClickerPrefs
ProfessionalAutoClickerPrefs_FILES = ACRootListController.m
ProfessionalAutoClickerPrefs_INSTALL_PATH = /Library/PreferenceBundles
ProfessionalAutoClickerPrefs_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/bundle.mk
