include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ProfessionalAutoClickerPrefs
ProfessionalAutoClickerPrefs_FILES = ACRootListController.m
ProfessionalAutoClickerPrefs_FRAMEWORKS = UIKit
ProfessionalAutoClickerPrefs_PRIVATE_FRAMEWORKS = Preferences
ProfessionalAutoClickerPrefs_INSTALL_PATH = /Library/PreferenceBundles
ProfessionalAutoClickerPrefs_CFLAGS = -fobjc-arc -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk
